"""empty message

Revision ID: 58bc11d91219
Revises: a7f8acb69b94
Create Date: 2022-02-20 21:58:41.925225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bc11d91219'
down_revision = 'a7f8acb69b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
